monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.pci-0000_07_00.6.HiFi__Headphones__sink"
      }
    ]
    actions = {
      update-props = {
        node.description = "Headphones/Wired Speaker",
      }
    }
  }
]
