preload = ~/Pictures/Wallpapers/wall1.png
preload = ~/Pictures/Wallpapers/wall2.png

wallpaper = eDP-1, ~/Pictures/Wallpapers/wall1.png
wallpaper = desc:Dell Inc. DELL S2721HN 54TF193, ~/Pictures/Wallpapers/wall2.png
wallpaper = , ~/Pictures/Wallpapers/wall2.png

splash=false
