env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
env = __VK_LAYER_NV_optimus,NVIDIA_only
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = SSH_AUTH_SOCK,$XDG_RUNTIME_DIR/gcr/ssh
env = NVD_GPU,0
env = LIBVA_DRIVER_NAME,nvidia
# env = WLR_DRM_DEVICES,$HOME/.config/hypr/internalcard

windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = hypridle

exec-once = dbus-update-activation-environment --all
exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store
$config_dir = ~/.config/hypr/hyprland

exec-once = waybar & hyprpaper & swaync

exec-once = ~/.config/hypr/scripts/handle_monitor_connect.sh

exec-once = udiskie &
exec-once = foot -s &

exec-once = hyprctl dispatch moveworkspacetomonitor "2 0"
exec-once = hyprctl dispatch moveworkspacetomonitor "1 1"

source=$config_dir/userSettings.conf

source=$config_dir/monitors.conf

source=$config_dir/settings.conf

source=$config_dir/keyBinds.conf

source=$config_dir/unsupported.conf

source=$config_dir/rules.conf

exec-once = ~/.config/hypr/scripts/gamemode.sh
