$scriptsDir = ~/.config/hypr/scripts/
$mainMod = SUPER # Sets "Windows" key as main modifier

bind = $mainMod, Q, killactive,
bind = $mainMod+Ctrl+Alt, backspace, exit,
bind = $mainMod, V, togglefloating,
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle
bind = $mainMod, F, fullscreen, # dwindle

bind = Alt, C, centerwindow, # dwindle
bind = Alt, R, resizeactive,exact 50% 50% # dwindle

bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# System function control
bind = ,XF86MonBrightnessUp, exec, $scriptsDir/brightness-ctrl.sh +
bind = ,XF86MonBrightnessDown, exec, $scriptsDir/brightness-ctrl.sh -
bind = ,XF86AudioRaiseVolume, exec, $scriptsDir/volume-ctrl.sh +
bind = ,XF86AudioLowerVolume, exec, $scriptsDir/volume-ctrl.sh -
bind = ,XF86AudioMute, exec, $scriptsDir/volume-ctrl.sh mute
bind = ,XF86AudioPlay, exec, playerctl play-pause
bind = ,XF86AudioNext, exec, playerctl next || playerctl position `bc <<< "100 * $(playerctl metadata mpris:length) / 1000000 / 100"`
bind = ,XF86AudioPrev, exec, playerctl previous

bind = ,Print, exec, $scriptsDir/screenshot.sh -f
bind = ,Shift+Print, exec, $scriptsDir/screenshot.sh -w
bind = ,Ctrl+Print, exec, $scriptsDir/screenshot.sh -s

bind = WIN, F1, exec, ~/.config/hypr/scripts/gamemode.sh

# application
bind = $mainMod, T, exec, $terminal
bind = $mainMod, B, exec, $browser
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, backslash, exec, $menu

# will switch to a submap called resize
bind=$mainMod,R,submap,resize

# will start a submap called "resize"
submap=resize

# sets repeatable binds for resizing the active window
binde=,right,resizeactive,20 0
binde=,left,resizeactive,-20 0
binde=,up,resizeactive,0 -20
binde=,down,resizeactive,0 20

# use reset to go back to the global submap
bind=,escape,submap,reset 

# will reset the submap, which will return to the global submap
submap=reset
# keybinds further down will be global again...

bindm = ALT, mouse:272, resizewindow

bind = $mainMod+Shift, h,swapwindow, l
bind = $mainMod+Shift, j,swapwindow, d
bind = $mainMod+Shift, k,swapwindow, u
bind = $mainMod+Shift, l,swapwindow, r
