# ######## Window rules ########
# windowrule = noblur,.*
# windowrule = opacity 0.89 override 0.89 override, .* # Applies transparency to EVERY WINDOW

windowrule = float, ^(blueberry.py)$
windowrule = float, ^(steam)$
windowrule = float, ^(guifetch)$ # FlafyDev/gifetch
windowrulev2 = tile, class:(dev.warp.Warp)
windowrulev2 = float, title:^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
windowrule = center, title:^(Open File)(.*)$
windowrule = center, title:^(Select a File)(.*)$
windowrule = center, title:^(Choose wallpaper)(.*)$
windowrule = center, title:^(Open Folder)(.*)$
windowrule = center, title:^(Save As)(.*)$
windowrule = center, title:^(Library)(.*)$
windowrule = center, title:^(File Upload)(.*)$
windowrulev2 = float, class:^(Raspberry Pi Imager)(.*)$
windowrulev2 = float, class:^(1Password)(.*)$
windowrulev2 = float, title:^(Quick Access — 1Password)(.*)$
windowrulev2 = stayfocused, title:^(Quick Access — 1Password)$
windowrulev2 = center, title:^(Quick Access — 1Password)$
windowrulev2 = minsize 550 404, title:^(Quick Access — 1Password)$
windowrulev2 = minsize 800 800, class:^(rviz2)$
windowrulev2 = float, class:^(rviz2)$
windowrulev2 = center, class:^(rviz2)$
windowrulev2 = stayfocused, class:^(hyprpolkitagent)$
windowrulev2 = stayfocused,  class:(pinentry-)(.*)

# Dialogs
windowrule=float,title:^(Open File)(.*)$
windowrule=float,title:^(Select a File)(.*)$
windowrule=float,title:^(Choose wallpaper)(.*)$
windowrule=float,title:^(Open Folder)(.*)$
windowrule=float,title:^(Save As)(.*)$
windowrule=float,title:^(Library)(.*)$
windowrule=float,title:^(File Upload)(.*)$

# Tearing
windowrule=immediate,.*\.exe
windowrulev2=immediate,class:(steam_app)

# No shadow for tiled windows
windowrulev2 = noshadow,floating:0
