general { 
    gaps_in = 0
        gaps_out = 0

        border_size = 2

        col.active_border = rgba(36aaa2ee) rgba(d7c29dee) 45deg
        col.inactive_border = rgba(595959aa)

        resize_on_border = false 

        allow_tearing = false

        layout = dwindle
}

decoration {
    rounding = 0

        active_opacity = 1
        inactive_opacity = 0.95
        fullscreen_opacity = 1.0

        dim_inactive = true
        dim_strength = 0.05

        drop_shadow = true
        shadow_range = 15
        shadow_render_power = 3
        col.shadow = rgba(1a1a1aee)

        blur {
            enabled = true
                size = 8
                passes = 2

                vibrancy = 0.1696
        }
}

animations {
    enabled = true

        bezier = myBezier, 0.05, 0.95, 0.1, 1.05

        animation = windows, 1, 5, myBezier
        animation = windowsOut, 1, 5, default, popin 80%
        animation = border, 1, 7, default
        animation = borderangle, 1, 6, default
        animation = fade, 1, 5, default
        animation = workspaces, 1, 4, default
}

dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        preserve_split = true # You probably want this
}

master {
    new_status = master
}

misc { 
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
                disable_splash_rendering = true
                vfr=true
                }

                input {
                kb_layout = us
                kb_variant =
                kb_model =
                kb_options =
                repeat_rate = 60
                repeat_delay = 205
                kb_rules =

                follow_mouse = 1

                sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
                touchpad {
                disable_while_typing = true
                natural_scroll = true
                clickfinger_behavior = false
                middle_button_emulation = true
                tap-to-click = true
                drag_lock = false
                }
                }

gestures {
    workspace_swipe = true
        workspace_swipe_fingers = 3
        workspace_swipe_distance = 500
        workspace_swipe_invert = true
        workspace_swipe_min_speed_to_force = 30
        workspace_swipe_cancel_ratio = 0.5
        workspace_swipe_create_new = true 
        workspace_swipe_forever = true
#workspace_swipe_use_r = true #uncomment if wanted a forever create a new workspace with swipe right
}

binds {
    workspace_back_and_forth = true
        allow_workspace_cycles = true
}
