$terminal = footclient
$discord = vesktop
$browser = firefox-beta
$fileManager = dolphin
$menu = rofi -show-icons -show drun

cursor {
    no_hardware_cursors = true
    enable_hyprcursor = true
    warp_on_change_workspace = true
}

env = XCURSOR_THEME,Catppuccin-Macchiato-Dark
env = XCURSOR_SIZE,36
env = HYPRCURSOR_THEME,Catppuccin-Macchiato-Dark
env = HYPRCURSOR_SIZE,36

exec-once = [workspace 1 silent] (sleep 1 && $terminal) &
exec-once = [workspace 2 silent] $browser
# exec-once = [workspace 8 silent] $discord

layerrule = blur, logout_dialog

#workspace=1,monitor:desc:Dell Inc. DELL S2721HN 54TF193,persistent:true,default:true
#workspace=3,monitor:desc:Dell Inc. DELL S2721HN 54TF193,persistent:true
#workspace=5,monitor:desc:Dell Inc. DELL S2721HN 54TF193,persistent:true
#workspace=7,monitor:desc:Dell Inc. DELL S2721HN 54TF193,persistent:true
#workspace=9,monitor:desc:Dell Inc. DELL S2721HN 54TF193,persistent:true

#workspace=2,monitor=eDP-1,persistent:true
#workspace=4,monitor=eDP-1,persistent:true
#workspace=6,monitor=eDP-1,persistent:true
#workspace=8,monitor=eDP-1,persistent:true
#workspace=10,monitor=eDP-1,persistent:true
