$terminal = footclient
$discord = vesktop
$browser = chromium
$fileManager = nautilus
$menu = rofi -show-icons -show drun
$browser = chromium

cursor {
    no_hardware_cursors = true
    enable_hyprcursor = true
    warp_on_change_workspace = true
}

env = XCURSOR_THEME,Catppuccin-Macchiato-Dark
env = XCURSOR_SIZE,36
env = HYPRCURSOR_THEME,Catppuccin-Macchiato-Dark
env = HYPRCURSOR_SIZE,36

exec-once = [workspace 1 silent] while true; do $terminal; if [ $? -eq 0 ]; then break; fi; done
exec-once = [workspace 2 silent] $browser
# exec-once = [workspace 8 silent] $discord

layerrule = blur, logout_dialog
